import { Hero } from './hero';

export const HEROES: Hero[] = [
  { id: 1, name: 'Tyler', photo: '../assets/tyler.jpg' },
  { id: 2, name: 'Alecx', photo: '../assets/alecx.jpg' },
  { id: 3, name: 'Kenn', photo: '../assets/kenn.jpg' },
  { id: 4, name: 'Tom', photo: '../assets/tom.jpg' },
  { id: 5, name: 'Dave', photo: '../assets/dave.jpg' },
  { id: 6, name: 'Gunjan', photo: '../assets/6.jpeg' },
    { id: 8, name: 'Kerry', photo: '../assets/8.jpeg' },
  { id: 9, name: 'George', photo: '../assets/9.jpeg' },
  { id: 10, name: 'Jayshon', photo: '../assets/10.jpeg' },
  { id: 11, name: 'Cory', photo: '../assets/11.jpeg' },
  { id: 12, name: 'Luke', photo: '../assets/12.jpeg' },
  { id: 14, name: 'Alex', photo: '../assets/14.jpeg' },
  { id: 15, name: 'Christian', photo: '../assets/15.jpeg' },
  { id: 16, name: 'Cody', photo: '../assets/16.jpeg' },
  { id: 17, name: 'Josh', photo: '../assets/17.jpeg' },
  { id: 18, name: 'Jason', photo: '../assets/18.jpeg' },
  { id: 19, name: 'Abby', photo: '../assets/19.jpeg' },
  { id: 21, name: 'Connor', photo: '../assets/21.jpeg' },
  { id: 22, name: 'Jake', photo: '../assets/22.jpeg' },
  { id: 23, name: 'Emily', photo: '../assets/23.jpeg' },
  { id: 24, name: 'Kyle', photo: '../assets/24.jpeg' },
  { id: 26, name: 'Sam', photo: '../assets/26.jpeg' },
  { id: 27, name: 'Kristen', photo: '../assets/27.jpeg' },
  { id: 28, name: 'Keagan', photo: '../assets/28.jpeg' },
  { id: 29, name: 'Nic', photo: '../assets/29.jpeg' },
  { id: 30, name: 'Donavan', photo: '../assets/30.jpeg' },
  { id: 31, name: 'Walter', photo: '../assets/31.jpeg' },
  { id: 7, name: 'William', photo: '../assets/7.jpeg' },
  { id: 13, name: 'Jacob', photo: '../assets/13.jpeg' },
  { id: 20, name: 'Ben', photo: '../assets/20.jpeg' },
  { id: 32, name: 'Dorian', photo: '../assets/32.jpeg' },
  { id: 33, name: 'Avery', photo: '../assets/33.jpg' },
  { id: 25, name: 'Alex S', photo: '../assets/25.jpeg' },
];